# Day 27: Matrix with Numpy

#### 1. Giới thiệu 

Ma trận là một công cụ toán học quan trọng trong trí tuệ nhân tạo (AI). Chúng được sử dụng để biểu diễn và thao tác dữ liệu, cũng như trong các phép tính tuyến tnh cần thiết cho việc học máy(Machine learning) và học sâu (deep learning)

#### 2. Định nghĩa ma trận

Một ma trận là một mảng chủ nhật của các số, sắp xếp theo hàng và cột. Ma trận A với m hàng và n cột được ký hiệu là:

$$
A = \begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix}
$$


#### 3. Các phép toán cơ bản 

##### Phép cộng ma trận

Hai ma trận A và B có cùng kích thước có thể được cộng lại với nhau bằng cách cộng từng phần tử tương ứng:
$$
\text{C = A + B với } c_{ij} = a_{ij}+ b_{ij}
$$

##### Phép nhân ma trận
Phép nhân hai ma trận A và B chỉ có thể thực hiện được khi số cột của A bằng hằng số hàng của B. Phần ử cij của ma trận tích C= AB được tính như sau:
$$
c_{ij} = \sum_{k=1}^{n} a_{ik} b_{kj}
$$

##### Ma trận chuyển vị
Ma trận chuyển vị của ma trận A, Ký hiệu là A^T, là ma trận được tạo ra bằng cách hoán đổi hàng và cột của A:
$$
(A^T)_{ij}=A_{ji}
$$
##### Ma trận nghịch đảo 
Ma trận nghịch đảo của ma trận vuông A, ký hiệu là A^(-1), là ma trận sao cho:
$$
AA^{-1}=A^{-1}A=1
$$
với I là ma trận đơn vị. Không phải mọi ma trận vuông đều có ma trạn nghịch đảo.
##### Định thức
Định thức là một giá trị vô hướng có thể tính toán từ một ma trận vuông và cung cấp thông tin quan trọng về ma trận đó. Định tức của ma trận A được ký hiệu là det(A) hoặc |A|.

### 4. Ứng dụng của ma trận trong AI
Ma trận được sử dụng rộng rãi trong AI, đặc biệt là trong các lĩnh vực sau:


#### Biểu diễn dữ liệu 
Dữ liệu trong AI thường được biểu diễn dưới dạng ma trận. Ví dụ, một hình ảnh có thể được biểu diễn như một ma trận của các giá trị pixel 


#### Mạng Nơ-ron Nhân Tạo
Ma trận được sử dụng để biểu diễn các trọng số và tính toàn trong các lớp của mạng nơ-ron nhân tạo 


#### Phân tích dữ liệu
Các phép toán ma trận được sử dụng trong nhiều thuật toán học máy để phân tích và biến đổi dữ liệu, như PCA (Phân tích thành phần chính)

### 5. Bài tập

In [ ]:
import numpy as np

#### Bài tập 1: Tạo ma trận
Viết mã Python để tạo một ma trận 3X3 với các phần tử ngẫu nhieen

In [1]:
matrix = np.random.randint(0, 10, (3, 3))
print("Ma trận 3x3 với các phần tử ngẫu nhiên:\n", matrix)

Ma trận 3x3 với các phần tử ngẫu nhiên:
 [[2 2 5]
 [1 9 0]
 [9 1 7]]


#### Bài tập 2: Phép cộng ma trận
Viết mã Python để cộng hai ma trận 3x3

In [13]:
matrix1 = np.random.randint(0, 10, (3, 3))
print("Ma trận 1 :\n", matrix1)
matrix2 = np.random.randint(0, 10, (3, 3))
print("Ma trận 2 :\n", matrix2)

matrix_sum = matrix1 + matrix2

print("Tổng của hai ma trận: \n", matrix_sum)

Ma trận 1 :
 [[6 3 7]
 [1 2 0]
 [4 2 5]]
Ma trận 2 :
 [[1 9 7]
 [0 9 1]
 [7 4 4]]
Tổng của hai ma trận: 
 [[ 7 12 14]
 [ 1 11  1]
 [11  6  9]]
Tổng của hai ma trận custom: 
 [array([ 7, 12, 14]), array([ 1, 11,  1]), array([11,  6,  9])]


#### Bài tập 3: Phép nhân ma trận
Viết mã Python để nhân hai ma trận 3x3

In [4]:
matrix1 = np.random.randint(0, 10, (3, 3))
print("Ma trận 1 :\n", matrix1)
matrix2 = np.random.randint(0, 10, (3, 3))
print("Ma trận 2:\n", matrix2)

matrix_product = np.dot(matrix1, matrix2)
print("Tích của hai ma trận:\n", matrix_product)

Ma trận 1 :
 [[7 8 8]
 [8 4 3]
 [9 8 4]]
Ma trận 2:
 [[6 6 8]
 [5 4 9]
 [7 3 8]]
Tích của hai ma trận:
 [[138  98 192]
 [ 89  73 124]
 [122  98 176]]


#### Bài tập 4: Ma trận chuyển vị
Viết mã Python để tìm ma trận chuyển vị của một ma trận 3x3

In [5]:
matrix= np.random.randint(0, 10, (3, 3))
print("Ma trận :\n",matrix)

matrix_transpose = np.transpose(matrix)
print("Ma trận chuyển vị:\n", matrix_transpose)


Ma trận :
 [[7 8 1]
 [9 9 8]
 [5 3 6]]
Ma trận chuyển vị:
 [[7 9 5]
 [8 9 3]
 [1 8 6]]


#### Bài Tập 5: Ma trận nghịch đảo
Viết mã Python để tìm ma trận nghịch đảo của một ma trận 3x3 (nếu có) 

In [10]:
matrix  = np.random.randint(0, 10, (3, 3))
print("Ma trận :\n", matrix)
try:
    matrix_inverse=np.linalg.inv(matrix)
    print("Ma trận nghịch đảo: \n",matrix_inverse)
except np.linalg.LinAlgError:
    print("Ma trận không khả nghịch")

Ma trận nghịch đảo: 
 [[ 0.16078431 -0.08235294  0.01176471]
 [-0.07058824  0.01176471  0.14117647]
 [-0.14901961  0.24705882 -0.03529412]]


#### Bài tập 6: Tính định thức ma trận
Viết mã Python để tính định thức của một ma trận 3x3

In [12]:
matrix=np.random.randint(0, 10, (3, 3))
print("Ma trận :\n", matrix)

det=np.linalg.det(matrix)
print("Định thức của ma trận:\n", det)

Ma trận :
 [[4 1 5]
 [9 9 1]
 [8 6 1]]
Định thức của ma trận:
 -79.0
