## Day 28: Enisum in NumPy

### 1. Khái niệm Enisum trong Python

Enisum là một hàm trong thư viện NumPy của Python, viết tắt của "Einstein summation" giúp chúng ta thực hiện các phép tính trên ma trận một cách ngắn gọn và hiệu quả. einsum cho phép bạn chỉ định các phép toán trên các mảng đa chiều bằng cách sử dụng ký hiệu Einstein. Ký hiệu này cho phép bn mô tả các phép tính như tổng, nhân chéo, và nhiều phép toán phức tạp khác một cách trực quan và ngắn gọn. cú pháp của einsum là 

> numpy.einsum(subcripts, *operands, out=None)

Trong đó: 
- subcripts là một chuỗi mô tả các phép toán.
- operands là các mảng đầu vào bạn muốn thực hiện phép tính  

### 2. Bài tập

In [1]:
import numpy as np

#### Bài tập 1: tính tổng của các cột trong ma trận
sử dụng einsum để tính tổng của từng cột trong ma trận 2d

In [5]:
A = np.arange(1, 10).reshape(3, 3)

column_sums = np.einsum('ij ->j', A)
print(column_sums)

[12 15 18]


#### Bài tập 2: Tính tích vô hướng của hai ma trận
Sử dụng einsum để tính tích vô hướng (dot product) của hai ma trận 2D

In [52]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
dot_product = np.einsum('ij,ij->', A, B)
print(dot_product)

70


#### Bài tập 3: Tính tổng các phần tử trên đường chéo chính của ma trận
Sử dụng einsum để tính tổng các phần tử trên đường chéo chính của ma trận 2D

In [31]:
A = np.arange(1, 10).reshape(3, 3)
print("Ma trận: \n", A)
diagonal_sum = np.einsum('ii->', A)
print("Tổng các phần tử trên đường chéo chính của ma trận là: ", diagonal_sum)

Ma trận: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tổng các phần tử trên đường chéo chính của ma trận là:  15


#### Bài tập 4: Nhân hai ma trận 2D
Sử dụng einsum để thực hiện phép nhân hai ma trận 2D

In [35]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.einsum('ij,jk->ik', A, B)
print("Tích hai ma trận: \n", C)

Tích hai ma trận: 
 [[19 22]
 [43 50]]


#### Bài tập 5: Tính tích ngoài của hai vector
Sử dụng einsum để tính tích ngoài (outer product) của hai vector

In [39]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
outer_product = np.einsum('i,j->ij', A, B)
print("Tích ngoài của hai vector: \n", outer_product)

Tích ngoài của hai vector: 
 [ 4 10 18]


#### Bài tập 6: Tính ma trận Gram của một tensor 3D
Sử dụng einsum để tính ma trận Gram của một tensor 3D có kích thước (chanels, height, width) 


In [55]:
def gram_matrix(tensor):
	channels, height, width = tensor.shape
	features = tensor.reshape(channels, height * width)
	gram = np.einsum('ik,jk->ij', features, features)
	return gram


In [56]:
tensor = np.random.rand(3, 4, 4)
gram = gram_matrix(tensor)
print(gram)

[[4.70774163 3.68145184 3.33441414]
 [3.68145184 4.57090561 3.41608804]
 [3.33441414 3.41608804 5.65283441]]
